export function emailAddress(value:string){const email=value.trim().toLowerCase();if(email.length>254||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('กรอกอีเมลให้ถูกต้อง');return email;}
export function phoneNumber(value:string){let phone=value.trim().replace(/[\s()-]/g,'');if(/^0[689]\d{8}$/.test(phone))phone=`+66${phone.slice(1)}`;if(!/^\+[1-9]\d{7,14}$/.test(phone))throw new Error('กรอกเบอร์ไทย 10 หลัก หรือเบอร์พร้อมรหัสประเทศ เช่น +66');return phone;}
export function otpCode(value:string){const code=value.trim();if(!/^\d{6}$/.test(code))throw new Error('กรอกรหัส OTP 6 หลัก');return code;}
export function utf8Bytes(value:string){let bytes=0;for(const char of value){const cp=char.codePointAt(0)!;bytes+=cp<=0x7f?1:cp<=0x7ff?2:cp<=0xffff?3:4;}return bytes;}
export function newPassword(value:string,confirm:string){if(value.length<10)throw new Error('ใช้รหัสผ่านอย่างน้อย 10 ตัวอักษร');if(utf8Bytes(value)>72)throw new Error('รหัสผ่านยาวเกินไป กรุณาลดจำนวนตัวอักษร');if(value!==confirm)throw new Error('รหัสผ่านทั้งสองช่องไม่ตรงกัน');return value;}
const privateRoutes=new Set(['/','/record','/transactions','/reports','/slips','/settings','/account','/line-preview','/mascot-preview']);
export function safeReturnPath(value:unknown):string{if(typeof value!=='string'||!value.startsWith('/')||value.startsWith('//')||/[\\\u0000-\u001f]/.test(value))return '/';try{const url=new URL(value,'https://app.invalid');if(url.origin!=='https://app.invalid'||!privateRoutes.has(url.pathname))return '/';const q=new URLSearchParams();for(const key of ['id','slip']){const v=url.searchParams.get(key);if(v&&/^[a-f\d-]{36}$/i.test(v))q.set(key,v);}return url.pathname+(q.size?`?${q}`:'');}catch{return '/';}}
export function assertCallbackUrl(value:string,expected:string){let actual:URL,allowed:URL;try{actual=new URL(value);allowed=new URL(expected);}catch{throw new Error('ลิงก์เข้าสู่ระบบไม่ถูกต้อง');}if(actual.protocol!==allowed.protocol||actual.host!==allowed.host||actual.pathname!==allowed.pathname||actual.username||actual.password)throw new Error('ลิงก์เข้าสู่ระบบไม่ถูกต้อง');if(actual.searchParams.has('error'))throw new Error('การเข้าสู่ระบบถูกยกเลิกหรือลิงก์หมดอายุ กรุณาลองใหม่');const code=actual.searchParams.get('code');if(!code||code.length>2048||actual.hash)throw new Error('ลิงก์ไม่ครบหรือหมดอายุ กรุณาขอลิงก์ใหม่จากเครื่องนี้');return code;}
export function authMessage(error:unknown,fallback='ดำเนินการไม่สำเร็จ กรุณาลองใหม่'):string{
  const code=typeof error==='object'&&error!==null&&'code' in error?String(error.code):'';
  const messages:Record<string,string>={invalid_credentials:'อีเมลหรือรหัสผ่านไม่ถูกต้อง',email_not_confirmed:'กรุณายืนยันอีเมลก่อนเข้าสู่ระบบ',otp_expired:'รหัสไม่ถูกต้องหรือหมดอายุ กรุณาขอรหัสใหม่',over_email_send_rate_limit:'ส่งอีเมลบ่อยเกินไป กรุณารอสักครู่',over_sms_send_rate_limit:'ส่งรหัสบ่อยเกินไป กรุณารอสักครู่',over_request_rate_limit:'ลองบ่อยเกินไป กรุณารอสักครู่',user_already_exists:'ช่องทางนี้มีบัญชีอยู่แล้ว กรุณาเข้าสู่บัญชีเดิมก่อน',identity_already_exists:'Google นี้เชื่อมกับบัญชีอื่นอยู่ กรุณาเข้าสู่บัญชีเดิม',email_exists:'อีเมลนี้อยู่ในบัญชีอื่น กรุณาเข้าสู่บัญชีเดิม',phone_exists:'เบอร์นี้อยู่ในบัญชีอื่น กรุณาเข้าสู่บัญชีเดิม',same_password:'กรุณาใช้รหัสผ่านใหม่ที่ต่างจากเดิม',reauthentication_needed:'กรุณาเข้าสู่ระบบอีกครั้งก่อนเปลี่ยนรหัสผ่าน',reauthentication_not_valid:'รหัสยืนยันไม่ถูกต้องหรือหมดอายุ',weak_password:'รหัสผ่านยังไม่ผ่านข้อกำหนด ลองรหัสที่ยาวขึ้น',provider_disabled:'ช่องทางนี้ยังไม่เปิดใช้งาน',email_address_not_authorized:'ยังตั้งค่าการส่งอีเมลไม่ครบ',validation_failed:'ตรวจสอบข้อมูลที่กรอกอีกครั้ง'};
  if(code)return messages[code]??fallback;
  // Never echo upstream response bodies, callback descriptions or tokens.
  return fallback;
}
