import {QrDetails} from './qr-details';
import React,{useState,useEffect} from 'react';
import {View,Modal,ScrollView,Image,Pressable,Switch} from 'react-native';
import {useRouter} from 'expo-router';
import {Receipt,ChevronRight,Clock,Check,TriangleAlert,Link,X,Settings as SettingsIcon} from 'lucide-react-native';
import {sourceCodes,money,parseMoney,type Slip} from '@expense/core';
import {useData,newId} from './state';
import {T,Card,Button,ActionRow,Field,Choices,Badge,C,s} from './ui';
import {Loading,MotionPressable,useMotion} from './motion';
import {ModalCompanion} from './modal-companion';
const names={ttb:'ttb',kplus:'K-PLUS',krungthai:'Krungthai',make:'MAKE'};
const statuses:Record<Slip['status'],string>={queued:'รอประมวลผล',processing:'กำลังอ่าน QR',needs_details:'รอกรอกข้อมูล',qr_unreadable:'อ่าน QR ไม่ได้',duplicate:'สลิปซ้ำ',linked:'บันทึกแล้ว',failed:'ไม่สำเร็จ'};
export function Slips(){const {reduced}=useMotion();const [imageLoading,setImageLoading]=useState(false);const state=useData(),router=useRouter(),[filter,setFilter]=useState('pending'),[bank,setBank]=useState('all'),[selected,setSelected]=useState<Slip|null>(null),[image,setImage]=useState(''),[message,setMessage]=useState(''),[linkId,setLinkId]=useState<string|null>(null),[busy,setBusy]=useState(false),[deleteTarget,setDeleteTarget]=useState<Slip|'all'|null>(null);
  const items=state.data.slips.filter(v=>(bank==='all'||v.source_code===bank)&&(filter==='all'||(filter==='pending'?!['linked','duplicate'].includes(v.status):v.status===filter))).sort((a,b)=>b.uploaded_at.localeCompare(a.uploaded_at));
  function open(slip:Slip){setSelected(slip);setMessage('');setImage('');setLinkId(null);}
  useEffect(()=>{let alive=true;if(!selected){setImageLoading(false);return;}
    setImageLoading(true);
    state.image(selected.id).then(value=>{if(alive)setImage(value);}).catch(e=>{if(alive)setMessage(e instanceof Error?e.message:'โหลดภาพไม่สำเร็จ');}).finally(()=>{if(alive)setImageLoading(false);});
    return()=>{alive=false;};
  },[selected?.id]);
  async function retry(slip:Slip){if(state.demo){setMessage('โหมดตัวอย่างไม่ประมวลผลภาพจริง');return;}setBusy(true);try{await state.call(`/slips/${slip.id}/retry`,'POST');await state.refresh();setSelected(null);}catch(e){setMessage(e instanceof Error?e.message:'ลองใหม่ไม่สำเร็จ');}finally{setBusy(false);}}
  async function deleteSlips(){if(!deleteTarget||busy)return;setBusy(true);setMessage('');try{
    if(state.demo){const ids=new Set(state.data.slips.filter(v=>!v.transaction_id&&(deleteTarget==='all'||v.id===deleteTarget.id||v.duplicate_of===deleteTarget.id)).map(v=>v.id));state.updateLocal(d=>({...d,slips:d.slips.filter(v=>!ids.has(v.id))}));}
    else {await state.call(deleteTarget==='all'?'/slips':`/slips/${deleteTarget.id}`,'DELETE');await state.refresh();}
    setSelected(null);setDeleteTarget(null);setMessage('ลบสลิปแล้ว ไฟล์ต้นฉบับยังอยู่ใน Drive');
  }catch(e){setMessage(e instanceof Error&&e.message==='IMPORT_RUNNING'?'กำลังนำเข้าสลิป รอให้เสร็จแล้วลองลบอีกครั้ง':'ลบไม่สำเร็จ ตรวจว่ารัน 004_delete_slips.sql แล้ว');}finally{setBusy(false);}}
  return <View style={s.section}><Card style={{gap:14}}><View style={s.between}><View><T style={s.bold}>กล่องสลิป</T><T style={s.muted}>QR ที่ไม่มีข้อมูลยอด ต้องเติมรายละเอียดก่อนรวมยอด</T></View></View><Button secondary loading={busy} onPress={()=>{setBusy(true);setMessage('');state.call('/slips/ocr-backfill','POST').then(r=>setMessage(`เข้าคิว OCR ${r.queued} สลิป จะประมวลผลเมื่อคิวทำงาน`)).catch(e=>setMessage(e.message==='OCR_NOT_CONFIGURED'?'ยังไม่เปิด OCR กรุณาตั้งค่าระบบก่อน':e.message)).finally(()=>setBusy(false));}}>อ่าน OCR สลิปที่ค้าง</Button><Button secondary disabled={busy||!state.data.slips.some(v=>!v.transaction_id)} onPress={()=>setDeleteTarget('all')}>ลบสลิปที่ยังไม่บันทึกทั้งหมด</Button>{!!message&&!selected&&<T accessibilityRole="alert" style={s.muted}>{message}</T>}<Choices value={filter} onChange={setFilter} items={[{id:'pending',name:'รอข้อมูล'},{id:'all',name:'ทั้งหมด'},{id:'linked',name:'บันทึกแล้ว'},{id:'duplicate',name:'ซ้ำ'}]}/><Choices value={bank} onChange={setBank} items={[{id:'all',name:'ทุกแหล่ง'},...sourceCodes.map(id=>({id,name:names[id]}))]}/></Card>
    {items.map(v=><MotionPressable accessibilityRole="button" key={v.id} onPress={()=>void open(v)}><Card style={{gap:12}}><View style={s.between}><View style={s.row}><View style={{backgroundColor:'#eef0fc',padding:13,borderRadius:15}}><Receipt color={C.primary} size={22}/></View><View style={{flexShrink:1}}><T style={s.bold}>{names[v.source_code]}</T><T style={s.muted}>อัปโหลด {new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',dateStyle:'medium',timeStyle:'short'}).format(new Date(v.uploaded_at))}</T></View></View><ChevronRight color={C.muted} size={18}/></View><View style={s.between}><T style={[s.muted,{flex:1}]} numberOfLines={1}>{v.name??'สลิปธนาคาร'}</T><Badge text={statuses[v.status]} color={v.status==='linked'?C.green:v.status==='duplicate'?C.muted:'#b18c4a'}/></View></Card></MotionPressable>)}{!items.length&&<Card><T style={s.muted}>ไม่มีสลิปในตัวกรองนี้</T></Card>}
    <Modal visible={!!selected} transparent animationType={reduced?'none':'fade'} onRequestClose={()=>setSelected(null)}><View style={{flex:1,backgroundColor:'#24334f66',justifyContent:'center',padding:20}}><ScrollView contentContainerStyle={{maxWidth:650,width:'100%',alignSelf:'center',paddingVertical:20}}><Card enterDelay={0} style={{gap:17}}>{selected&&<><ModalCompanion title={`สลิป ${names[selected.source_code]}`} pose={selected.status==='linked'?'celebrate':['needs_details','qr_unreadable','failed','duplicate'].includes(selected.status)?'thinking':'reading'} action={<MotionPressable accessibilityRole="button" accessibilityLabel="ปิดรายละเอียดสลิป" onPress={()=>setSelected(null)} style={{width:44,height:44,alignItems:'center',justifyContent:'center'}}><X size={18} color={C.muted}/></MotionPressable>}/><Badge text={statuses[selected.status]}/>{imageLoading&&<Loading label="กำลังโหลดภาพสลิป"/>}{!!image&&<Image source={{uri:image}} style={{width:'100%',height:420,borderRadius:14}} resizeMode="contain" accessibilityLabel="ภาพสลิปธนาคาร"/>}{!!message&&<T style={s.muted}>{message}</T>}{selected.error_code&&<T style={s.muted}>สถานะ: {selected.error_code}</T>}<QrDetails slip={selected}/><View><T style={s.label}>ข้อความจาก QR</T><T selectable style={{fontSize:11,color:'#6d7890'}}>{selected.qr_payload??'ยังอ่าน QR ไม่ได้'}</T></View>
      {!selected.transaction_id&&<Button secondary disabled={busy} onPress={()=>setDeleteTarget(selected)}>ลบสลิปนี้</Button>}{selected.status==='duplicate'&&<T>สลิปนี้ซ้ำกับต้นฉบับ ไม่เพิ่มยอดอีกครั้ง</T>}
      {selected.transaction_id?<ActionRow testID="slip-detail-actions"><Button secondary onPress={()=>setSelected(null)}>ปิด</Button><Button onPress={()=>{setSelected(null);router.push({pathname:'/record',params:{id:selected.transaction_id!}});}}>ดูรายการที่บันทึก</Button></ActionRow>:selected.status!=='duplicate'?<><ActionRow testID="slip-detail-actions">{!['queued','processing'].includes(selected.status)&&<Button secondary disabled={busy} onPress={()=>void retry(selected)}>ลองอ่าน QR ใหม่</Button>}<Button disabled={busy} onPress={()=>{setSelected(null);router.push({pathname:'/record',params:{slip:selected.id}});}}>{selected.ocr_details&&!selected.ocr_details.error?'ตรวจข้อมูลและบันทึก':'กรอกยอดและรายละเอียด'}</Button></ActionRow><T style={s.label}>หรือเชื่อมกับรายการที่บันทึกไว้แล้ว</T><Choices value={linkId} onChange={setLinkId} items={state.data.transactions.filter(t=>!state.data.slips.some(s=>s.transaction_id===t.id)).sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at)).map(t=>({id:t.id,name:`${t.note||t.counterparty||'รายการ'} · ${money(t.amount_satang)}`}))}/><ActionRow testID="slip-link-actions"><Button secondary disabled={busy} onPress={()=>setSelected(null)}>ปิด</Button><Button loading={busy} disabled={!linkId} onPress={()=>{setBusy(true);state.link(selected.id,linkId!).then(()=>setSelected(null)).catch(e=>setMessage(e.message)).finally(()=>setBusy(false));}}>เชื่อมรายการที่เลือก</Button></ActionRow></>:<Button secondary onPress={()=>setSelected(null)}>ปิด</Button>}
    </>}</Card></ScrollView></View></Modal>
    <Modal transparent visible={!!deleteTarget} animationType={reduced?'none':'fade'} onRequestClose={()=>{if(!busy)setDeleteTarget(null);}}><View style={{flex:1,backgroundColor:'#20305080',justifyContent:'center',padding:25}}><Card style={{maxWidth:430,width:'100%',alignSelf:'center',gap:18}}><ModalCompanion title={deleteTarget==='all'?'ลบสลิปที่ยังไม่บันทึกทั้งหมด?':'ลบสลิปนี้?'} pose="thinking"/><T>ลบสลิปและคิวอ่านในแอป ไฟล์ใน Drive และรายการเงินที่บันทึกแล้วจะยังอยู่ นำเข้าจาก Drive ใหม่ได้ สลิปซ้ำที่อ้างถึงใบที่ลบจะถูกลบด้วย</T>{!!message&&<T style={{color:C.red}}>{message}</T>}<ActionRow><Button secondary disabled={busy} onPress={()=>{setDeleteTarget(null);setMessage('');}}>ยกเลิก</Button><Button loading={busy} onPress={()=>void deleteSlips()}>ยืนยันลบ</Button></ActionRow></Card></View></Modal>
  </View>;
}
function SourceForm({code}:{code:typeof sourceCodes[number]}){const state=useData(),source=state.data.sources.find(s=>s.source_code===code),[folder,setFolder]=useState(source?.folder_id??''),[account,setAccount]=useState<string|null>(source?.account_id??null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function save(){if(!/^[A-Za-z0-9_-]{10,200}$/.test(folder.trim())){setMessage('ใส่ Folder ID จาก URL ของโฟลเดอร์ธนาคาร');return;}setBusy(true);try{if(state.demo){state.updateLocal(d=>({...d,sources:[...d.sources.filter(s=>s.source_code!==code),{id:newId(),source_code:code,folder_id:folder.trim(),account_id:account,last_scan_at:null,last_scan_status:null,scan_complete:false}]}));setMessage('บันทึกตัวอย่างในเครื่อง ยังไม่ได้เชื่อม Drive');}else{await state.call(`/sources/${code}`,'PUT',{folder_id:folder.trim(),account_id:account});await state.refresh();setMessage('บันทึกแล้ว');}}catch(e){setMessage(e instanceof Error?e.message:'บันทึกไม่สำเร็จ');}finally{setBusy(false);}}
  return <Card style={{gap:12}}><View style={s.between}><T style={s.bold}>{names[code]}</T><Badge text={source?.last_scan_status==='success'?'ตรวจสำเร็จ':source?.last_scan_status==='failed'?'ตรวจไม่สำเร็จ':source?'รอตรวจ':'ยังไม่เชื่อม'} color={source?.last_scan_status==='failed'?C.red:C.primary}/></View><Field label="Folder ID ของธนาคาร (ไม่ใช่โฟลเดอร์วันที่)" value={folder} onChangeText={setFolder} autoCapitalize="none"/><T style={s.label}>บัญชีเงินจริงที่เกี่ยวข้อง</T><Choices value={account} onChange={setAccount} items={state.data.accounts.filter(a=>a.kind==='bank')}/><T style={s.muted}>แหล่งสลิปไม่ใช้ตัดสินว่าเป็นรายรับหรือรายจ่าย</T><Button secondary loading={busy} onPress={()=>void save()}>บันทึก {names[code]}</Button>{!!message&&<T style={s.muted}>{message}</T>}{source?.last_scan_at&&<T style={s.muted}>ตรวจล่าสุด {new Date(source.last_scan_at).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'})}</T>}</Card>;
}
export function Settings(){const router=useRouter(),motion=useMotion();const state=useData(),[budget,setBudget]=useState(String(state.data.settings.budget_satang/100)),[message,setMessage]=useState(''),[command,setCommand]=useState(''),[accountName,setAccountName]=useState(''),[bankCode,setBankCode]=useState(''),[kind,setKind]=useState('bank'),[categoryName,setCategoryName]=useState(''),[busy,setBusy]=useState(false),[ruleParty,setRuleParty]=useState(''),[ruleCategory,setRuleCategory]=useState<string|null>(null);
  async function action(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn();await state.refresh();}catch(e){setMessage(e instanceof Error?e.message:'ทำรายการไม่สำเร็จ');}finally{setBusy(false);}}
  useEffect(()=>setBudget(String(state.data.settings.budget_satang/100)),[state.data.settings.budget_satang]);
  return <View style={s.section}><Card style={{gap:14}}><T style={s.bold}>การแสดงผล</T><Button secondary onPress={()=>router.push('/mascot-preview')}>ดูท่าตัวละคร</Button><View style={s.between}><View style={{flex:1,gap:5}}><T>ลดการเคลื่อนไหว</T><T style={s.muted}>{motion.system?'เปิดตามการตั้งค่าของอุปกรณ์':'ปิดเอฟเฟกต์เคลื่อนไหว เหลือหน้าจอและสถานะโหลด'}</T></View><Switch accessibilityLabel="ลดการเคลื่อนไหว" value={motion.reduced} disabled={motion.system} onValueChange={motion.setManual} trackColor={{false:'#dce2ef',true:'#7a80df'}} thumbColor="white"/></View></Card><Card style={{gap:14}}><T style={s.bold}>บัญชีและการเข้าสู่ระบบ</T><T style={s.muted}>อีเมล รหัสผ่าน Google และเบอร์ที่เชื่อมกับบัญชีเดิม</T><Button secondary onPress={()=>router.push('/account')}>จัดการบัญชีผู้ใช้</Button></Card><Card style={{gap:14}}><T style={s.bold}>งบรายเดือน</T><Field label="จำนวนเงิน (บาท) · 0 หมายถึงยังไม่ตั้งงบ" value={budget} onChangeText={setBudget} keyboardType="decimal-pad"/><Button disabled={busy} onPress={()=>void action(async()=>{const n=budget.trim()==='0'?0:parseMoney(budget);if(n===null)throw new Error('จำนวนเงินไม่ถูกต้อง');if(state.demo)state.updateLocal(d=>({...d,settings:{...d.settings,budget_satang:n}}));else await state.call('/settings','PATCH',{budget_satang:n});setMessage('บันทึกงบแล้ว');})}>บันทึกงบ</Button></Card>
    <Card style={{gap:14}}><View style={s.between}><T style={s.bold}>แจ้งเตือน LINE</T><Badge text={state.data.settings.line_connected?state.data.settings.line_blocked?'ถูกบล็อก':'เชื่อมแล้ว':'ยังไม่เชื่อม'} color={state.data.settings.line_connected?C.green:C.muted}/></View><T style={s.muted}>รายวันหลัง 23:15 · สัปดาห์จันทร์ 08:00 · เดือนวันที่ 1 เวลา 08:00</T><T style={s.muted}>รายวันรวมข้อมูลถึง 23:00 มีสลิปรอกรอกจะแจ้งจำนวนพร้อมยอดที่มี</T><ActionRow testID="line-settings-actions"><Button secondary onPress={()=>router.push('/line-preview')}>ดูตัวอย่าง LINE Flex</Button><Button disabled={busy} onPress={()=>void action(async()=>{if(state.demo)throw new Error('โหมดตัวอย่างไม่เชื่อม LINE จริง');const r=await state.call('/line/link-code','POST');setCommand(r.command);})}>สร้างรหัสเชื่อม LINE</Button></ActionRow>{!!command&&<View style={{gap:8}}><T style={s.muted}>คัดลอกข้อความนี้ส่งในแชต LINE OA ของระบบภายใน 5 นาที แล้วกดโหลดข้อมูลใหม่</T><T selectable style={[s.bold,{fontFamily:'NotoLatinBold'}]}>{command}</T></View>}{state.data.settings.line_connected&&<ActionRow testID="line-connection-actions"><Button secondary disabled={busy} onPress={()=>void action(async()=>{await state.call('/line/connection','DELETE');setCommand('');})}>ยกเลิกการเชื่อม LINE</Button><Button secondary loading={state.loading} disabled={busy} onPress={()=>void state.refresh()}>โหลดสถานะใหม่</Button></ActionRow>}</Card>
    <View style={s.between}><T style={[s.bold,{fontSize:18,flex:1,minWidth:0}]}>แหล่งสลิป Google Drive</T><Button secondary disabled={busy} onPress={()=>void action(async()=>{if(state.demo)throw new Error('โหมดตัวอย่างไม่เชื่อม Drive จริง');const r=await state.call('/sync','POST');setMessage(`เข้าคิวตรวจ ${r.queued} โฟลเดอร์ จะทำงานในรอบถัดไป`);})}>ซิงก์ตอนนี้</Button></View>{sourceCodes.map(code=><SourceForm key={`${code}:${state.data.sources.find(s=>s.source_code===code)?.id??'new'}`} code={code}/>)}
    <Card style={{gap:14}}><T style={s.bold}>เพิ่มบัญชี</T><Choices value={kind} onChange={setKind} items={[{id:'bank',name:'บัญชีธนาคาร'},{id:'cash',name:'เงินสด'}]}/><Field label="ชื่อบัญชี" value={accountName} onChangeText={setAccountName}/>{kind==='bank'&&<Field label="รหัสธนาคาร (ถ้ามี)" value={bankCode} onChangeText={setBankCode}/>}<Button secondary disabled={busy} onPress={()=>void action(async()=>{if(!accountName.trim())throw new Error('กรอกชื่อบัญชี');const input={name:accountName.trim(),kind:kind as 'bank'|'cash',bank_code:kind==='bank'?(bankCode||null):null,color:'#6d83d8'};if(state.demo)state.updateLocal(d=>({...d,accounts:[...d.accounts,{id:newId(),...input}]}));else await state.call('/accounts','POST',input);setAccountName('');setBankCode('');setMessage('เพิ่มบัญชีแล้ว');})}>เพิ่มบัญชี</Button></Card>
    <Card style={{gap:14}}><T style={s.bold}>เพิ่มหมวดหมู่</T><Field label="ชื่อหมวด" value={categoryName} onChangeText={setCategoryName}/><Button secondary disabled={busy} onPress={()=>void action(async()=>{if(!categoryName.trim())throw new Error('กรอกชื่อหมวด');const input={name:categoryName.trim(),color:'#967bd6'};if(state.demo)state.updateLocal(d=>({...d,categories:[...d.categories,{id:newId(),...input}]}));else await state.call('/categories','POST',input);setCategoryName('');setMessage('เพิ่มหมวดแล้ว');})}>เพิ่มหมวดหมู่</Button></Card>
    <Card style={{gap:14}}><T style={s.bold}>กฎจัดหมวดจากผู้รับ</T><Field label="ชื่อผู้รับหรือร้านค้า ตรงกับรายการ" value={ruleParty} onChangeText={setRuleParty}/><Choices items={state.data.categories} value={ruleCategory} onChange={setRuleCategory}/><Button secondary disabled={busy} onPress={()=>void action(async()=>{if(!ruleParty.trim()||!ruleCategory)throw new Error('กรอกชื่อและเลือกหมวด');const rule={counterparty:ruleParty.trim(),category_id:ruleCategory};if(state.demo)state.updateLocal(d=>({...d,rules:[...d.rules.filter(r=>r.counterparty!==rule.counterparty),{id:newId(),...rule}]}));else await state.call('/rules','POST',rule);setMessage('บันทึกกฎแล้ว');})}>บันทึกกฎ</Button>{state.data.rules.map(r=><T key={r.id} style={s.muted}>{r.counterparty} → {state.data.categories.find(c=>c.id===r.category_id)?.name}</T>)}</Card>
    {!!message&&<Card><T style={{color:message.includes('สำเร็จ')||message.includes('ไม่')?C.red:C.primary}}>{message}</T></Card>}<T style={s.muted}>ภาพสลิปเก็บใน Drive · ระบบอ่าน QR เท่านั้น · ไม่มี OCR หรือบริการตรวจสลิปภายนอก</T>
  </View>;
}
