import React,{useEffect,useRef} from 'react';
import {View,Text,Pressable,TextInput,StyleSheet,useWindowDimensions,ScrollView} from 'react-native';
import {LinearGradient} from 'expo-linear-gradient';
import {usePathname,useRouter} from 'expo-router';
import {LayoutDashboard,ArrowLeft,ArrowLeftRight,Plus,ChartNoAxesCombined,Receipt,Settings,Wallet,LogOut,RefreshCw,ChevronRight,CloudOff} from 'lucide-react-native';
import {useData} from './state';
import {DataSkeleton,MotionPressable,Reveal,Spinner} from './motion';

export const C={bg:'#f3f5fa',ink:'#253044',muted:'#657187',primary:'#5668df',border:'#e8ecf3',white:'#ffffff',green:'#237f6b',red:'#b34e63'};
export const s=StyleSheet.create({text:{fontFamily:'NotoThai',color:C.ink,fontSize:14},bold:{fontFamily:'NotoThaiBold',color:C.ink},muted:{fontFamily:'NotoThai',color:C.muted,fontSize:12},title:{fontFamily:'NotoThaiBold',color:C.ink,fontSize:26},card:{backgroundColor:'white',borderRadius:22,padding:20,borderWidth:1,borderColor:'#edf0f6',boxShadow:'0 5px 20px rgba(44,65,110,0.035)'},row:{flexDirection:'row',alignItems:'center',gap:12},between:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},input:{backgroundColor:'#f6f8fc',borderWidth:1,borderColor:C.border,borderRadius:14,paddingHorizontal:14,paddingVertical:12,fontFamily:'NotoThai',fontSize:14,color:C.ink,minHeight:48},label:{fontFamily:'NotoThaiBold',color:'#626e84',fontSize:12,marginBottom:7},grid:{flexDirection:'row',flexWrap:'wrap',gap:14},section:{gap:16},button:{backgroundColor:C.primary,borderRadius:14,paddingHorizontal:16,paddingVertical:12,alignItems:'center',justifyContent:'center',minHeight:46},badge:{borderRadius:10,paddingHorizontal:10,paddingVertical:4}});
export function T({children,style,...props}:React.ComponentProps<typeof Text>){return <Text {...props} style={[s.text,style]}>{children}</Text>;}
export function Card({children,style,enterDelay}: {children:React.ReactNode;style?:any;enterDelay?:number}){const {width}=useWindowDimensions(),cardStyle=[s.card,width<1000&&{padding:17,borderRadius:21,borderColor:'#ffffff',boxShadow:'0 4px 16px rgba(44,65,110,.035)'},style];return enterDelay===undefined?<View style={cardStyle}>{children}</View>:<Reveal delay={enterDelay} style={cardStyle}>{children}</Reveal>;}
export function Button({children,onPress,secondary=false,disabled=false,loading=false,style}:{children:React.ReactNode;onPress:()=>void;secondary?:boolean;disabled?:boolean;loading?:boolean;style?:any}){return <MotionPressable accessibilityRole="button" accessibilityState={{disabled:disabled||loading,busy:loading}} disabled={disabled||loading} onPress={onPress} style={[s.button,secondary&&{backgroundColor:'#edf0fa'},disabled&&!loading&&{opacity:.5},{flexDirection:'row',gap:7,minWidth:0,flexShrink:1},style]}>{loading&&<Spinner size={16} color={secondary?C.primary:'#ffffff'}/>}<T style={{fontFamily:'NotoThaiBold',color:secondary?C.primary:'white',fontSize:13,minWidth:0,flexShrink:1,textAlign:'center'}}>{children}</T></MotionPressable>;}
// Paired actions stay side by side even on narrow screens; labels may wrap inside.
export function ActionRow({children,testID}:{children:React.ReactNode;testID?:string}){return <View testID={testID} style={{flexDirection:'row',alignItems:'stretch',gap:10}}>{React.Children.map(children,child=>React.isValidElement<{style?:any}>(child)?React.cloneElement(child,{style:[child.props.style,{flex:1,minWidth:0,flexBasis:0}]}):child)}</View>;}
export function Field({label,...props}:React.ComponentProps<typeof TextInput>&{label:string}){return <View style={{gap:0}}><T style={s.label}>{label}</T><TextInput accessibilityLabel={label} placeholderTextColor='#a1aabc' {...props} style={[s.input,props.style]}/></View>;}
export function Choices({items,value,onChange,segmented=false}:{items:{id:string;name:string}[];value:string|null;onChange:(id:string)=>void;segmented?:boolean}){return <View style={{flexDirection:'row',gap:segmented?3:8,flexWrap:segmented?'nowrap':'wrap',backgroundColor:segmented?'#e9edf4':undefined,borderRadius:segmented?16:undefined,padding:segmented?4:0}}>{items.map(i=><MotionPressable key={i.id} accessibilityRole="button" accessibilityState={{selected:value===i.id}} onPress={()=>onChange(i.id)} style={{flex:segmented?1:undefined,minWidth:0,maxWidth:'100%',flexShrink:1,alignItems:segmented?'center':undefined,backgroundColor:segmented?(value===i.id?'white':'transparent'):value===i.id?'#e9edff':'#f5f7fb',borderRadius:12,paddingHorizontal:segmented?7:12,paddingVertical:9,minHeight:44,justifyContent:'center',borderWidth:segmented?0:1,borderColor:value===i.id?'#bbc5ff':C.border}}><T style={{fontSize:12,minWidth:0,flexShrink:1,textAlign:segmented?'center':undefined,color:value===i.id?C.primary:C.muted,fontFamily:value===i.id?'NotoThaiBold':'NotoThai'}}>{i.name}</T></MotionPressable>)}</View>;}
export function Badge({text,color=C.primary}:{text:string;color?:string}){return <View style={[s.badge,{backgroundColor:`${color}14`}]}><T style={{fontSize:11,color,fontFamily:'NotoThaiBold'}}>{text}</T></View>;}
export function Hero({label,amount,children}:{label:string;amount:string;children?:React.ReactNode}){const {width}=useWindowDimensions(),compact=width<1000;return <LinearGradient colors={['#5277e5','#8160d2']} start={{x:0,y:0}} end={{x:1,y:1}} style={{borderRadius:24,padding:compact?20:25,gap:10,overflow:'hidden'}}><View style={s.between}><T style={{color:'#eef0ff',fontFamily:'NotoThaiBold',fontSize:compact?12:14}}>{label}</T><Reveal delay={120}><Wallet color='#d8deff' size={22}/></Reveal></View><Reveal delay={60} replayKey={amount}><T style={{color:'white',fontFamily:'NotoLatinBold',fontSize:compact?32:38}}>{amount}</T></Reveal>{children}</LinearGradient>;}
const nav=[{path:'/',name:'ภาพรวม',icon:LayoutDashboard},{path:'/transactions',name:'รายการ',icon:ArrowLeftRight},{path:'/record',name:'บันทึก',icon:Plus},{path:'/reports',name:'รายงาน',icon:ChartNoAxesCombined},{path:'/slips',name:'สลิป',icon:Receipt},{path:'/settings',name:'ตั้งค่า',icon:Settings}];
export function Frame({children}:{children:React.ReactNode}) {
  const {width}=useWindowDimensions(),wide=width>=1000,path=usePathname(),router=useRouter(),state=useData();
  const scroll=useRef<ScrollView>(null);
  useEffect(()=>{scroll.current?.scrollTo({y:0,animated:false});},[path]);
  if(state.error)return <ScrollView style={{flex:1,backgroundColor:C.bg}} contentContainerStyle={{flexGrow:1,justifyContent:'center',alignItems:'center',padding:28}}><View testID="data-fetch-error" style={{width:'100%',maxWidth:400,alignItems:'center',gap:18}}><View style={{width:88,height:88,borderRadius:28,backgroundColor:'#e9edff',alignItems:'center',justifyContent:'center'}}><CloudOff size={42} color={C.primary}/></View><T accessibilityRole="header" style={[s.bold,{fontSize:24,textAlign:'center'}]}>โหลดข้อมูลไม่สำเร็จ</T><T style={{color:C.muted,textAlign:'center',lineHeight:24}}>เชื่อมต่อระบบไม่ได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง</T><T accessibilityRole="alert" style={{fontSize:12,color:C.red,textAlign:'center'}}>{state.error}</T><View style={{width:'100%',marginTop:8}}><Button loading={state.loading} onPress={()=>void state.refresh()}>ลองโหลดใหม่</Button></View></View></ScrollView>;
  const mobileNav=nav.filter(item=>!['/record','/slips'].includes(item.path));
  const link=(item:typeof nav[number],mobile=false)=>{const active=path===item.path||(mobile&&item.path==='/transactions'&&['/record','/slips'].includes(path));const Icon=item.icon;return <MotionPressable key={item.path} accessibilityLabel={item.name} accessibilityRole="button" accessibilityState={{selected:active}} onPress={()=>router.push(item.path as any)} style={{minHeight:mobile?49:44,flexDirection:mobile?'column':'row',alignItems:'center',justifyContent:mobile?'center':undefined,gap:mobile?3:12,paddingVertical:mobile?5:13,paddingHorizontal:mobile?4:16,borderRadius:mobile?18:14,backgroundColor:active?(mobile?'#edf1fa':'#e9edff'):'transparent',flex:mobile?1:undefined}}><Icon size={mobile?20:20} color={active?C.primary:'#8c97a9'}/><T style={{color:active?C.primary:C.muted,fontSize:mobile?10:13,fontFamily:active?'NotoThaiBold':'NotoThai'}}>{mobile&&item.path==='/'?'หน้าหลัก':item.name}</T></MotionPressable>;};
  return <View style={{flex:1,backgroundColor:C.bg,flexDirection:wide?'row':'column'}}>
    {wide&&<View style={{width:235,padding:24,paddingTop:34,backgroundColor:'#fff',borderRightWidth:1,borderColor:C.border,gap:25}}><View style={s.row}><View style={{backgroundColor:'#eef0ff',padding:10,borderRadius:14}}><Wallet color={C.primary}/></View><View><T style={[s.bold,{fontSize:20}]}>Expense</T><T style={[s.muted,{fontFamily:'NotoLatin'}]}>TRACKER</T></View></View><View style={{gap:6}}>{nav.map(i=>link(i))}</View><View style={{flex:1}}/><View style={{backgroundColor:'#f6f8fd',borderRadius:16,padding:14,gap:6}}><T style={[s.bold,{fontSize:12}]}>อัปโหลดอัตโนมัติ 23:00</T><T style={s.muted}>ttb · K-PLUS · Krungthai · MAKE</T></View><Button secondary onPress={()=>void state.signOut()}>ออกจากระบบ</Button></View>}
    <View style={{flex:1}}><ScrollView ref={scroll} keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:wide?32:16,paddingTop:wide?28:18,paddingBottom:wide?35:104}}><View style={{maxWidth:wide?1180:520,width:'100%',alignSelf:'center',gap:wide?24:14}}>
      <View style={[s.between,{minHeight:wide?undefined:42}]}><View style={{flex:1,minWidth:0,gap:3}}>{wide?<T style={s.muted}>สมุดบันทึกเงินของคุณ</T>:path==='/'?<T style={{fontSize:10,color:C.muted}}>{new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',day:'numeric',month:'long',year:'numeric'}).format(new Date())}</T>:null}<View style={{flexDirection:'row',alignItems:'center',gap:8}}>{!wide&&path!=='/'&&<MotionPressable accessibilityRole="button" accessibilityLabel="กลับหน้าหลัก" hitSlop={8} onPress={()=>router.push('/')} style={{width:30,height:34,alignItems:'center',justifyContent:'center',borderRadius:12,backgroundColor:'#ffffff'}}><ArrowLeft size={16} color='#71809a'/></MotionPressable>}<T style={[s.bold,{fontSize:wide?24:path==='/'?19:21,fontFamily:!wide&&path==='/'?'NotoLatinBold':'NotoThaiBold',flexShrink:1}]}>{!wide&&path==='/'?'Expense Tracker':nav.find(i=>i.path===path)?.name??(path==='/account'?'บัญชีผู้ใช้':path==='/line-preview'?'LINE Flex':path==='/mascot-preview'?'ตัวละคร':'รายละเอียด')}</T></View></View><View style={{flexDirection:'row',alignItems:'center',gap:wide?12:7}}>{state.demo&&wide&&<Badge text="ข้อมูลตัวอย่าง" color='#c18c34'/>}<MotionPressable accessibilityRole="button" accessibilityLabel="โหลดข้อมูลใหม่" hitSlop={5} accessibilityState={{busy:state.loading,disabled:state.loading}} disabled={state.loading} onPress={()=>void state.refresh()} style={{width:36,height:36,alignItems:'center',justifyContent:'center',backgroundColor:'white',borderRadius:12}}>{state.loading?<Spinner size={16}/>:<RefreshCw size={16} color={C.primary}/>}</MotionPressable>{!wide&&(path==='/settings'?<MotionPressable accessibilityRole="button" accessibilityLabel="ออกจากระบบ" hitSlop={5} onPress={()=>void state.signOut()} style={{width:36,height:36,alignItems:'center',justifyContent:'center',backgroundColor:'white',borderRadius:12}}><LogOut size={16} color={C.muted}/></MotionPressable>:<MotionPressable accessibilityRole="button" accessibilityLabel="เปิดตั้งค่า" hitSlop={5} onPress={()=>router.push('/settings')} style={{width:36,height:36,alignItems:'center',justifyContent:'center',backgroundColor:'white',borderRadius:12}}><Settings size={16} color={C.muted}/></MotionPressable>)}</View></View>
      {state.demo&&<T accessibilityLabel="โหมดตัวอย่าง บันทึกเฉพาะเครื่องนี้ ไม่มีการเชื่อม Drive หรือส่ง LINE" style={[s.muted,{color:'#998458',fontSize:wide?12:10}]}>{wide?'โหมดตัวอย่าง · บันทึกในเครื่องนี้เท่านั้น ไม่มีการเชื่อม Drive หรือส่ง LINE':'โหมดตัวอย่าง · ข้อมูลเฉพาะเครื่องนี้ · ไม่ส่ง LINE'}</T>}
      {!!state.error&&<Card><T style={{color:C.red}}>{state.error}</T><Button secondary onPress={()=>void state.refresh()}>ลองโหลดใหม่</Button></Card>}
      {state.loading&&state.data.accounts.length===0?<DataSkeleton/>:<Reveal replayKey={path}>{children}</Reveal>}
    </View></ScrollView>
    {!wide&&<View style={{position:'absolute',bottom:12,left:14,right:14,maxWidth:520,alignSelf:'center',marginHorizontal:'auto',backgroundColor:'#fffffff5',borderRadius:26,padding:6,flexDirection:'row',gap:4,boxShadow:'0 8px 24px rgba(32,55,90,.12)',borderWidth:1,borderColor:'white'}}>{mobileNav.map(i=>link(i,true))}</View>}</View>
  </View>;
}

