import React,{useState,useRef,useEffect} from 'react';
import {View,useWindowDimensions} from 'react-native';
import {useRouter} from 'expo-router';
import {ArrowDownLeft,ArrowUpRight,ArrowLeftRight,ChevronRight,Plus,Receipt,Check,Wallet,Download,Search,Link as LinkIcon,Clock,TriangleAlert} from 'lucide-react-native';
import {money,thaiDate,rangeFor,summarize,parseMoney,transactionInput,transactionsCsv,type Summary,type Slip,type Transaction} from '@expense/core';
import {useData,newId} from './state';
import {T,Card,Button,Field,Choices,Badge,Hero,C,s} from './ui';
import {GrowingBar,MotionPressable,useMotion} from './motion';
import {MobileDashboard} from './mobile-dashboard';
import {DateField} from './calendar';
import {Companion} from './companion';

const dateLabel=(v:string)=>new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(v));
const kindName={income:'รายรับ',expense:'รายจ่าย',transfer:'โอนระหว่างบัญชี'};
const statusName:Record<Slip['status'],string>={queued:'รอประมวลผล',processing:'กำลังอ่าน QR',needs_details:'รอกรอกข้อมูล',qr_unreadable:'อ่าน QR ไม่ได้',duplicate:'สลิปซ้ำ',linked:'บันทึกแล้ว',failed:'ประมวลผลไม่สำเร็จ'};
function Empty({text='ยังไม่มีรายการในช่วงนี้'}:{text?:string}){return <View style={{padding:28,alignItems:'center',gap:10}}><Receipt color='#b7c1d1' size={30}/><T style={s.muted}>{text}</T></View>;}
function Bars({date,period='week'}:{date:string;period?:'day'|'week'|'month'}) {
  const {data}=useData();const r=rangeFor(date,period);const start=new Date(r.start),days=Math.min(31,Math.round((new Date(r.end).getTime()-start.getTime())/86400000));
  const values=Array.from({length:days},(_,i)=>{const d=thaiDate(new Date(start.getTime()+i*86400000)),range=rangeFor(d,'day');return {date:d,amount:summarize(data,range.start,range.end).expense};});
  const max=Math.max(...values.map(v=>v.amount),1);
  return <View style={{gap:12}}><View style={{height:145,flexDirection:'row',alignItems:'flex-end',gap:days>10?4:14}}>{values.map((v,i)=><View key={v.date} style={{flex:1,alignItems:'center',gap:8}}><GrowingBar label={`${v.date} รายจ่าย ${money(v.amount)}`} height={Math.max(4,v.amount/max*110)} color={v.date===date?'#6278df':'#c5bef2'} index={i} replayKey={`${period}:${date}`}/><T style={{fontSize:9,color:C.muted}}>{days>10?(i%5===0?String(i+1):''):new Intl.DateTimeFormat('th-TH',{timeZone:'Asia/Bangkok',weekday:'short'}).format(new Date(`${v.date}T12:00:00+07:00`))}</T></View>)}</View><T style={[s.muted,{fontSize:10}]}>รายจ่ายตามวันที่ทำรายการ · ไม่รวมโอนระหว่างบัญชี</T></View>;
}
function TransactionRow({item,onPress}:{item:Transaction;onPress?:()=>void}) {
  const {data}=useData(),{width}=useWindowDimensions(),compact=width<1000;const account=data.accounts.find(a=>a.id===item.account_id),category=data.categories.find(c=>c.id===item.category_id);const color=item.kind==='income'?C.green:item.kind==='transfer'?C.primary:C.red;const Icon=item.kind==='income'?ArrowDownLeft:item.kind==='transfer'?ArrowLeftRight:ArrowUpRight;
  return <MotionPressable accessibilityRole="button" onPress={onPress} style={{paddingVertical:14,paddingHorizontal:compact?12:0,marginTop:compact?8:0,backgroundColor:'white',borderRadius:compact?18:0,borderBottomWidth:compact?0:1,borderColor:'#f0f3f8',flexDirection:'row',gap:compact?10:12,alignItems:'center'}}><View style={{padding:compact?9:11,borderRadius:14,backgroundColor:`${category?.color??color}18`}}><Icon size={18} color={category?.color??color}/></View><View style={{flex:1,minWidth:0,gap:3}}><T style={[s.bold,{fontSize:13}]} numberOfLines={1}>{item.note||item.counterparty||kindName[item.kind]}</T><T style={[s.muted,{fontSize:10}]} numberOfLines={compact?1:undefined}>{account?.name} · {category?.name??'ยังไม่จัดหมวด'} · {dateLabel(item.occurred_at)}</T></View><View style={{alignItems:'flex-end',gap:3}}><T style={{fontFamily:'NotoLatinBold',color,fontSize:compact?13:14}}>{item.kind==='income'?'+':item.kind==='expense'?'-':''}{money(item.amount_satang)}</T><T style={[s.muted,{fontSize:10}]}>{item.source==='manual'?'บันทึกเอง':'จากสลิป'}</T></View></MotionPressable>;
}
export function Dashboard(){const {data}=useData(),router=useRouter(),{width}=useWindowDimensions(),wide=width>=1000,today=thaiDate(),r=rangeFor(today,'day'),summary=summarize(data,r.start,r.end),monthRange=rangeFor(today,'month'),month=summarize(data,monthRange.start,monthRange.end);const pending=data.slips.filter(v=>!['linked','duplicate'].includes(v.status)).length;
  if(!wide)return <MobileDashboard/>;
  return <View style={s.section}><Companion title="วันนี้บันทึกครบหรือยัง?" text="รวมทั้งเงินสดและรายการที่ไม่มีสลิปได้เลย"/><View style={[s.grid,{alignItems:'stretch'}]}><View style={{flexGrow:1,flexBasis:wide?'57%':'100%'}}><Hero label="วันนี้ใช้ไป" amount={money(summary.expense)}><View style={s.between}><T style={{color:'#e3e7ff',fontSize:12}}>{summary.count} รายการ · {new Intl.DateTimeFormat('th-TH',{dateStyle:'long',timeZone:'Asia/Bangkok'}).format(new Date())}</T><MotionPressable accessibilityRole="button" onPress={()=>router.push('/record')} style={{backgroundColor:'white',paddingHorizontal:15,paddingVertical:8,borderRadius:12}}><T style={{color:C.primary,fontSize:12,fontFamily:'NotoThaiBold'}}>+ บันทึก</T></MotionPressable></View></Hero></View><Card enterDelay={80} style={{flexGrow:1,flexBasis:wide?'37%':'100%',justifyContent:'space-between',gap:15}}><View style={s.between}><T style={s.bold}>งบเดือนนี้</T><Badge text={month.expense>data.settings.budget_satang?'เกินงบ':'รายจ่ายสะสม'} color={month.expense>data.settings.budget_satang?C.red:C.green}/></View><T style={{fontFamily:'NotoLatinBold',fontSize:26}}>{money(month.expense)} <T style={s.muted}>/ {money(data.settings.budget_satang)}</T></T><View style={{height:7,borderRadius:8,backgroundColor:'#edf0f7',overflow:'hidden'}}><View style={{width:`${Math.min(100,data.settings.budget_satang?month.expense/data.settings.budget_satang*100:0)}%`,height:7,backgroundColor:month.expense>data.settings.budget_satang?C.red:'#7e76dd'}}/></View><T style={s.muted}>{data.settings.budget_satang?`เหลืองบ ${money(Math.max(0,data.settings.budget_satang-month.expense))}`:'ยังไม่ได้ตั้งงบ'}</T></Card></View>
    <View style={s.grid}>{[{label:'รายรับวันนี้',value:money(summary.income),color:'#e6f5ef',icon:ArrowDownLeft,ink:C.green},{label:'เงินสุทธิวันนี้',value:money(summary.net),color:'#eaf0ff',icon:Wallet,ink:C.primary},{label:'สลิปรอข้อมูล',value:`${pending} สลิป`,color:'#fff3df',icon:Receipt,ink:'#c49243'}].map(x=><MotionPressable key={x.label} onPress={()=>router.push(x.label==='สลิปรอข้อมูล'?'/slips':'/transactions')} style={{flexGrow:1,flexBasis:wide?'30%':'45%',backgroundColor:x.color,borderRadius:19,padding:18,gap:10}}><x.icon size={20} color={x.ink}/><T style={[s.muted,{color:x.ink}]}>{x.label}</T><T style={[s.bold,{fontSize:20}]}>{x.value}</T></MotionPressable>)}</View>
    <View style={s.between}><T style={[s.bold,{fontSize:17}]}>แยกตามบัญชี · วันนี้</T><T style={s.muted}>รวมเงินสด</T></View><View style={s.grid}>{summary.byAccount.map((a,i)=><Card enterDelay={100+i*35} key={a.id} style={{flexGrow:1,flexBasis:wide?'17%':'43%',padding:16,gap:9}}><View style={s.row}><View style={{width:8,height:8,borderRadius:4,backgroundColor:a.color}}/><T style={[s.bold,{fontSize:12}]}>{a.name}</T></View><T style={{fontFamily:'NotoLatinBold',fontSize:19}}>{money(a.expense)}</T><T style={[s.muted,{fontSize:10}]}>รายรับ {money(a.income)}</T></Card>)}</View>
    <View style={s.grid}><Card enterDelay={200} style={{flexGrow:1,flexBasis:wide?'56%':'100%',gap:16}}><View style={s.between}><T style={s.bold}>รายจ่ายสัปดาห์นี้</T><Badge text="จันทร์ – อาทิตย์"/></View><Bars date={today}/></Card><Card enterDelay={240} style={{flexGrow:1,flexBasis:wide?'38%':'100%',gap:14}}><View style={s.between}><T style={s.bold}>หมวดที่ใช้ไป · เดือนนี้</T><MotionPressable accessibilityLabel="ดูรายงาน" onPress={()=>router.push('/reports')}><ChevronRight size={18} color={C.muted}/></MotionPressable></View>{month.byCategory.filter(c=>c.expense>0).slice(0,4).map(c=><View key={c.id} style={{gap:7}}><View style={s.between}><T style={{fontSize:12}}>{c.name}</T><T style={[s.bold,{fontSize:12}]}>{money(c.expense)}</T></View><View style={{height:5,backgroundColor:'#f0f3f8',borderRadius:5}}><View style={{height:5,borderRadius:5,width:`${month.expense?c.expense/month.expense*100:0}%`,backgroundColor:c.color}}/></View></View>)}{!month.expense&&<Empty/>}</Card></View>
    <Card style={{gap:8}}><View style={s.between}><T style={s.bold}>รายการล่าสุด</T><Button secondary onPress={()=>router.push('/transactions')}>ดูทั้งหมด</Button></View>{data.transactions.slice().sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at)).slice(0,5).map(t=><TransactionRow key={t.id} item={t} onPress={()=>router.push({pathname:'/record',params:{id:t.id}})}/>)}{!data.transactions.length&&<Empty text="เริ่มจากบันทึกรายการแรกของคุณ"/>}</Card>
  </View>;
}
export function Transactions(){const {data}=useData(),router=useRouter(),[search,setSearch]=useState(''),[kind,setKind]=useState('all'),[account,setAccount]=useState('all'),[category,setCategory]=useState('all'),[start,setStart]=useState(thaiDate().slice(0,7)+'-01'),[end,setEnd]=useState(thaiDate()),[page,setPage]=useState(0);
  const {width}=useWindowDimensions(),compact=width<1000,[filtersExpanded,setFiltersExpanded]=useState(false);
  const items=data.transactions.filter(t=>{const d=thaiDate(t.occurred_at);return d>=start&&d<=end&&(kind==='all'||t.kind===kind)&&(account==='all'||t.account_id===account)&&(category==='all'||(category==='none'?!t.category_id:t.category_id===category))&&`${t.note} ${t.counterparty}`.toLowerCase().includes(search.toLowerCase());}).sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at));
  useEffect(()=>setPage(0),[search,kind,account,category,start,end]);
  return <View style={s.section}><Card style={{gap:14}}><View style={s.between}><T style={s.bold}>ค้นหารายการ</T><Button onPress={()=>router.push('/record')}>+ บันทึก</Button></View><Field label="หมายเหตุหรือผู้เกี่ยวข้อง" value={search} onChangeText={setSearch} placeholder="ค้นหารายการ…"/>{compact&&<MotionPressable accessibilityRole="button" accessibilityLabel="แสดงหรือซ่อนตัวกรอง" accessibilityState={{expanded:filtersExpanded}} onPress={()=>setFiltersExpanded(!filtersExpanded)} style={{minHeight:44,paddingHorizontal:12,borderRadius:12,backgroundColor:'#f0f3fb',flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><T style={{fontSize:12,color:C.primary}}>ตัวกรอง{kind!=='all'||account!=='all'||category!=='all'?' · กำลังใช้':''}</T><T style={{fontSize:11,color:C.muted}}>{filtersExpanded?'ซ่อน −':'แสดง +'}</T></MotionPressable>}{(!compact||filtersExpanded)&&<><View style={s.grid}><View style={{flex:1,minWidth:130}}><DateField label="ตั้งแต่วันที่" value={start} onChange={setStart}/></View><View style={{flex:1,minWidth:130}}><DateField label="ถึงวันที่" value={end} onChange={setEnd}/></View></View><Choices value={kind} onChange={setKind} items={[{id:'all',name:'ทั้งหมด'},...Object.entries(kindName).map(([id,name])=>({id,name}))]}/><Choices value={account} onChange={setAccount} items={[{id:'all',name:'ทุกบัญชี'},...data.accounts]}/><Choices value={category} onChange={setCategory} items={[{id:'all',name:'ทุกหมวด'},...data.categories,{id:'none',name:'ยังไม่จัดหมวด'}]}/></>}</Card><Card style={compact?{padding:0,backgroundColor:'transparent',borderWidth:0,boxShadow:'none'}:undefined}><T style={s.muted}>{items.length} รายการ · แตะเพื่อดูหรือแก้ไข</T>{items.slice(page*20,page*20+20).map(t=><TransactionRow key={t.id} item={t} onPress={()=>router.push({pathname:'/record',params:{id:t.id}})}/>)}{!items.length&&<Empty/>}<View style={[s.between,{marginTop:15}]}><Button secondary style={{minWidth:90}} disabled={page===0} onPress={()=>setPage(page-1)}>ก่อนหน้า</Button><T style={s.muted}>{page+1} / {Math.max(1,Math.ceil(items.length/20))}</T><Button secondary style={{minWidth:90}} disabled={(page+1)*20>=items.length} onPress={()=>setPage(page+1)}>ถัดไป</Button></View></Card></View>;
}
export {Record} from './record';
export {Reports} from './reports';
