import {describe,it,expect,vi} from 'vitest';
import {emailAddress,phoneNumber,otpCode,newPassword,safeReturnPath,assertCallbackUrl,authMessage} from '../apps/app/src/auth-policy';
import {RememberedAuthStorage,memoryStore} from '../apps/app/src/auth-storage';
import {createAuthService} from '../apps/app/src/auth-service';
import {secureChunks} from '../apps/app/src/secure-chunks';

function fixture(flags={sms:false,google:true}){
  const persistent=memoryStore(),transient=memoryStore(),prefs=memoryStore(),storage=new RememberedAuthStorage(persistent,transient,prefs);
  const success=()=>({error:null});
  const auth={signInWithPassword:vi.fn().mockResolvedValue(success()),signInWithOtp:vi.fn().mockResolvedValue(success()),verifyOtp:vi.fn().mockResolvedValue(success()),resetPasswordForEmail:vi.fn().mockResolvedValue(success()),getUser:vi.fn().mockResolvedValue({data:{user:{id:'owner-a'}},error:null}),updateUser:vi.fn().mockResolvedValue(success()),signOut:vi.fn().mockResolvedValue(success()),linkIdentity:vi.fn().mockResolvedValue({data:{url:'https://accounts.google.com/test'},error:null}),signInWithOAuth:vi.fn().mockResolvedValue({data:{url:'https://accounts.google.com/test'},error:null}),exchangeCodeForSession:vi.fn().mockResolvedValue({data:{session:{user:{id:'owner-a'}},redirectType:null},error:null})};
  const launch=vi.fn().mockResolvedValue(undefined),service=createAuthService({auth} as any,{storage,...flags,redirect:()=> 'https://expense.example/auth/callback',launch});
  return {service,auth,storage,persistent,transient,prefs,launch};
}
describe('auth input and redirects',()=>{
  it('normalizes email and Thai phones without treating a number as verified',()=>{expect(emailAddress(' Owner@Example.com ')).toBe('owner@example.com');expect(phoneNumber('081-234-5678')).toBe('+66812345678');expect(phoneNumber('+66 81 234 5678')).toBe('+66812345678');expect(()=>phoneNumber('12345')).toThrow();expect(()=>emailAddress('not-email')).toThrow();expect(()=>otpCode('12ab56')).toThrow();expect(otpCode('123456')).toBe('123456');});
  it('requires matching new passwords with a bounded byte length',()=>{expect(newPassword('correct-password','correct-password')).toBe('correct-password');expect(()=>newPassword('short','short')).toThrow();expect(()=>newPassword('correct-password','different-password')).toThrow();expect(()=>newPassword('ก'.repeat(25),'ก'.repeat(25))).toThrow();});
  it('allows only local known routes and strips arbitrary callback/query values',()=>{for(const path of ['https://evil.test','//evil.test','/\\evil.test','/login','/auth/callback','/unknown','/reports\n'])expect(safeReturnPath(path)).toBe('/');expect(safeReturnPath('/reports?token=secret')).toBe('/reports');expect(safeReturnPath('/record?id=11111111-1111-4111-8111-111111111111&next=https://evil.test')).toBe('/record?id=11111111-1111-4111-8111-111111111111');});
  it('accepts only the expected PKCE callback, never fragments or upstream errors',()=>{const expected='https://expense.example/auth/callback';expect(assertCallbackUrl(expected+'?code=valid',expected)).toBe('valid');for(const url of ['https://evil.test/auth/callback?code=abc','https://expense.example/other?code=abc',expected+'#access_token=secret',expected+'?code=abc#access_token=secret',expected+'?error=access_denied&error_description=secret'])expect(()=>assertCallbackUrl(url,expected)).toThrow();expect(authMessage({message:'token=secret'})).not.toContain('secret');});
  it('supports the native deep-link callback and rejects alternate native schemes/paths',()=>{const expected='expense-tracker://auth/callback';expect(assertCallbackUrl(expected+'?code=native',expected)).toBe('native');for(const url of ['exp://auth/callback?code=native','expense-tracker://auth/other?code=native','expense-tracker://other/callback?code=native'])expect(()=>assertCallbackUrl(url,expected)).toThrow();});
});
describe('remembered session storage',()=>{
  it('keeps large native sessions within secure value limits and removes all parts on logout',async()=>{const raw=memoryStore(),values=new Map<string,string>(),checked={getItem:raw.getItem,setItem:async(k:string,v:string)=>{expect(new TextEncoder().encode(v).length).toBeLessThanOrEqual(1500);values.set(k,v);await raw.setItem(k,v);},removeItem:async(k:string)=>{values.delete(k);await raw.removeItem(k);}};const store=secureChunks(checked),data='token-ก😊'.repeat(700);await store.setItem('session',data);expect(await store.getItem('session')).toBe(data);await store.setItem('session','new-token');expect(await store.getItem('session')).toBe('new-token');await store.removeItem('session');expect(values.size).toBe(0);});
  it('preserves the last native session when a new chunk write fails',async()=>{const raw=memoryStore();let fail=false,calls=0;const store=secureChunks({...raw,setItem:async(k,v)=>{if(fail&&++calls===2)throw new Error('device-storage-full');await raw.setItem(k,v);}});await store.setItem('session','old-token');fail=true;await expect(store.setItem('session','x'.repeat(4000))).rejects.toThrow('device-storage-full');expect(await store.getItem('session')).toBe('old-token');});
  it('defaults to tab/memory storage and stores only a boolean preference',async()=>{const f=fixture();await f.storage.setItem('session','session-data');expect(await f.transient.getItem('session')).toBe('session-data');expect(await f.persistent.getItem('session')).toBeNull();expect(await f.storage.getRemember()).toBe(false);expect(await new RememberedAuthStorage(f.persistent,memoryStore(),f.prefs).getItem('session')).toBeNull();});
  it('moves known SDK session and PKCE keys in both directions and removes inactive copies',async()=>{const f=fixture();await f.storage.setItem('session','token');await f.storage.setItem('session-code-verifier','pkce');await f.storage.setRemember(true);expect(await f.transient.getItem('session')).toBeNull();expect(await f.persistent.getItem('session-code-verifier')).toBe('pkce');expect(await new RememberedAuthStorage(f.persistent,memoryStore(),f.prefs).getItem('session')).toBe('token');await f.storage.setRemember(false);expect(await f.persistent.getItem('session')).toBeNull();expect(await f.transient.getItem('session')).toBe('token');await f.storage.removeItem('session');expect(await f.storage.getItem('session')).toBeNull();});
  it('serializes storage writes during a remember switch',async()=>{const f=fixture();await Promise.all([f.storage.setItem('session','old'),f.storage.setRemember(true),f.storage.setItem('session','refreshed')]);expect(await f.persistent.getItem('session')).toBe('refreshed');expect(await f.transient.getItem('session')).toBeNull();});
});
describe('Supabase auth contracts',()=>{
  it('uses normalized email/password and never persists the password',async()=>{const f=fixture();await f.service.password('OWNER@example.com','password-never-store',true);expect(f.auth.signInWithPassword).toHaveBeenCalledWith({email:'owner@example.com',password:'password-never-store'});expect(await f.prefs.getItem('expense.auth.remember')).toBe('true');expect(await f.storage.getItem('password')).toBeNull();});
  it('sends email OTP without creating a public account and verifies the proper type',async()=>{const f=fixture();const target=await f.service.requestOtp('email',' Owner@example.com ',false);expect(f.auth.signInWithOtp).toHaveBeenCalledWith({email:'owner@example.com',options:{shouldCreateUser:false}});await f.service.verifyOtp('email',target,'123456');expect(f.auth.verifyOtp).toHaveBeenCalledWith({email:target,token:'123456',type:'email'});});
  it('blocks every SMS send/verify before any provider call while disabled',async()=>{const f=fixture();await expect(f.service.requestOtp('phone','0812345678',false)).rejects.toThrow('ยังไม่เปิดส่ง SMS');await expect(f.service.verifyOtp('phone','0812345678','123456')).rejects.toThrow();await expect(f.service.linkPhone('0812345678')).rejects.toThrow();await expect(f.service.verifyPhone('0812345678','123456')).rejects.toThrow();expect(f.auth.signInWithOtp).not.toHaveBeenCalled();expect(f.auth.verifyOtp).not.toHaveBeenCalled();expect(f.auth.updateUser).not.toHaveBeenCalled();});
  it('attaches a verified phone to the signed-in user, never creates a second account',async()=>{const f=fixture({sms:true,google:true});await f.service.linkPhone('0812345678');await f.service.verifyPhone('0812345678','123456');expect(f.auth.getUser).toHaveBeenCalled();expect(f.auth.updateUser).toHaveBeenCalledWith({phone:'+66812345678'});expect(f.auth.verifyOtp).toHaveBeenCalledWith({phone:'+66812345678',token:'123456',type:'phone_change'});expect(f.auth.signInWithOtp).not.toHaveBeenCalled();});
  it('keeps reset redirects on the expected PKCE callback and verifies before changing password',async()=>{const f=fixture();await f.service.forgot('owner@example.com');expect(f.auth.resetPasswordForEmail).toHaveBeenCalledWith('owner@example.com',{redirectTo:'https://expense.example/auth/callback'});f.auth.getUser.mockResolvedValueOnce({data:{user:null},error:null});await expect(f.service.updatePassword('correct-password','correct-password')).rejects.toThrow();expect(f.auth.updateUser).not.toHaveBeenCalled();await f.service.updatePassword('correct-password','correct-password');await f.service.revokeOtherSessions();expect(f.auth.updateUser).toHaveBeenCalledWith({password:'correct-password'});expect(f.auth.signOut).toHaveBeenCalledWith({scope:'others'});});
  it('recognizes recovery callbacks and exchanges a code once under concurrent mounts',async()=>{const f=fixture();f.auth.exchangeCodeForSession.mockResolvedValueOnce({data:{session:{user:{id:'owner-a'}},redirectType:'recovery'},error:null});const results=await Promise.all([f.service.callback('https://expense.example/auth/callback?code=one'),f.service.callback('https://expense.example/auth/callback?code=one')]);expect(results).toEqual([{recovery:true,linked:false},{recovery:true,linked:false}]);expect(f.auth.exchangeCodeForSession).toHaveBeenCalledTimes(1);});
  it('requires the same auth UUID after manual Google linking',async()=>{const f=fixture();await f.service.google(false,true);expect(f.auth.linkIdentity).toHaveBeenCalled();expect(await f.storage.getItem('expense.oauth.owner')).toBe('owner-a');f.auth.exchangeCodeForSession.mockResolvedValueOnce({data:{session:{user:{id:'attacker'}},redirectType:null},error:null});await expect(f.service.callback('https://expense.example/auth/callback?code=wrong-owner')).rejects.toThrow('ไม่ตรง');expect(f.auth.signOut).toHaveBeenCalledWith({scope:'local'});expect(await f.storage.getItem('expense.oauth.owner')).toBeNull();});
  it('retains one owner when linking Google succeeds and cleans cancelled flows',async()=>{const f=fixture();f.launch.mockResolvedValueOnce('https://expense.example/auth/callback?code=linked');expect(await f.service.google(true,true)).toEqual({recovery:false,linked:true});expect(await f.storage.getItem('expense.oauth.owner')).toBeNull();f.launch.mockResolvedValueOnce(null);await f.service.google(true,true);expect(await f.storage.getItem('expense.oauth.owner')).toBeNull();});
  it('clears the expected owner if manual OAuth linking fails before redirect',async()=>{const f=fixture();f.auth.linkIdentity.mockResolvedValueOnce({data:{url:null},error:{code:'identity_already_exists'}});await expect(f.service.google(false,true)).rejects.toThrow('บัญชีอื่น');expect(await f.storage.getItem('expense.oauth.owner')).toBeNull();expect(f.launch).not.toHaveBeenCalled();});
  it('maps expired and provider errors without exposing their bodies',async()=>{const f=fixture();f.auth.verifyOtp.mockResolvedValueOnce({error:{code:'otp_expired',message:'private-response'}});await expect(f.service.verifyOtp('email','owner@example.com','123456')).rejects.toThrow('หมดอายุ');f.auth.signInWithPassword.mockResolvedValueOnce({error:{message:'private-response'}});await expect(f.service.password('owner@example.com','pass',false)).rejects.not.toThrow('private-response');});
});
